id: f4e610c422dc4b82881ddb435c249b20
initial_creation_type: ocr
source_metadata:
  volumes:
    8fa1d1191ca2424cb5b415b504c5510c:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
